- name: install mysql
  hosts: mysql
  become: yes
  vars:
   login_root_password: ExpenseApp@1
   login_host: 172.31.86.159

  tasks:
  - name: ansible to install pymysql
    ansible.builtin.pip:
      name:
      - PyMySQL
      executable: pip3.9
      
  - name: install mysql
    ansible.builtin.package:
     name: mysql
     state: present

  - name: start the service
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes

  - name: connect to mysql server
    community.mysql.mysql_info:
     login_user: root
     login_password: "{{ login_root_password }}"
     login_host: "{{ login_host }}"
    ignore_errors: true
    register: mysql_info

  - name: print mysql info
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

  - name: setup MySQL root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ login_root_password }}"
    when: mysql_info.failed is true
  